# Generated by Django 4.2.7 on 2025-09-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='직책명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='직책코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '직책',
                'verbose_name_plural': '직책들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='조직명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='조직코드')),
                ('level', models.IntegerField(default=1, verbose_name='조직레벨')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('organization_type', models.CharField(choices=[('본부', '본부'), ('부서', '부서'), ('팀', '팀'), ('파트', '파트'), ('그룹', '그룹')], default='부서', max_length=20, verbose_name='조직유형')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='층')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='직원수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('assistant_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_organizations', to=settings.AUTH_USER_MODEL, verbose_name='차장')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL, verbose_name='조직장')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.organization', verbose_name='상위조직')),
            ],
            options={
                'verbose_name': '조직',
                'verbose_name_plural': '조직들',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='직위명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='직위코드')),
                ('level', models.IntegerField(verbose_name='직위레벨')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '직위',
                'verbose_name_plural': '직위들',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('change_type', models.CharField(choices=[('조직생성', '조직생성'), ('조직폐지', '조직폐지'), ('조직이동', '조직이동'), ('조직통합', '조직통합'), ('조직분할', '조직분할')], max_length=20, verbose_name='변경유형')),
                ('change_details', models.JSONField(blank=True, default=dict, verbose_name='변경세부사항')),
                ('effective_date', models.DateField(verbose_name='시행일')),
                ('status', models.CharField(choices=[('작성중', '작성중'), ('검토중', '검토중'), ('승인', '승인'), ('반려', '반려'), ('시행완료', '시행완료')], default='작성중', max_length=20, verbose_name='상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('approval_notes', models.TextField(blank=True, verbose_name='승인비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_org_changes', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('new_parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_change_requests', to='organization.organization', verbose_name='새 상위조직')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='대상조직')),
            ],
            options={
                'verbose_name': '조직개편 요청',
                'verbose_name_plural': '조직개편 요청들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('입사', '입사'), ('승진', '승진'), ('전보', '전보'), ('겸직', '겸직'), ('파견', '파견'), ('복귀', '복귀'), ('퇴사', '퇴사')], default='입사', max_length=20, verbose_name='발령유형')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('base_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='기본급')),
                ('allowances', models.JSONField(blank=True, default=dict, verbose_name='수당')),
                ('is_primary', models.BooleanField(default=True, verbose_name='주요발령')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_history', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.jobtitle', verbose_name='직책')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_history', to='organization.organization', verbose_name='조직')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.position', verbose_name='직위')),
            ],
            options={
                'verbose_name': '직원 조직이력',
                'verbose_name_plural': '직원 조직이력들',
                'ordering': ['-start_date'],
                'unique_together': {('employee', 'organization', 'start_date')},
            },
        ),
    ]
