# Generated by Django 4.2.7 on 2025-09-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자격증명')),
                ('issuing_organization', models.CharField(max_length=100, verbose_name='발급기관')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '자격증',
                'verbose_name_plural': '자격증들',
                'unique_together': {('name', 'issuing_organization')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='기술명')),
                ('category', models.CharField(choices=[('기술', '기술'), ('언어', '언어'), ('자격증', '자격증'), ('기타', '기타')], default='기술', max_length=50, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '기술',
                'verbose_name_plural': '기술들',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='회사명')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='부서')),
                ('position', models.CharField(max_length=50, verbose_name='직위')),
                ('job_description', models.TextField(verbose_name='업무 내용')),
                ('start_date', models.DateField(verbose_name='입사일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('reason_for_leaving', models.TextField(blank=True, verbose_name='퇴사사유')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='연봉')),
                ('is_current', models.BooleanField(default=False, verbose_name='현재 재직중')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '경력사항',
                'verbose_name_plural': '경력사항들',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('relationship', models.CharField(max_length=20, verbose_name='관계')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('is_primary', models.BooleanField(default=False, verbose_name='주요연락처')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '비상연락망',
                'verbose_name_plural': '비상연락망들',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, verbose_name='교육기관')),
                ('major', models.CharField(blank=True, max_length=50, verbose_name='전공')),
                ('degree', models.CharField(choices=[('고등학교', '고등학교'), ('전문대학', '전문대학'), ('대학교', '대학교'), ('석사', '석사'), ('박사', '박사'), ('기타', '기타')], default='대학교', max_length=20, verbose_name='학위')),
                ('start_date', models.DateField(verbose_name='입학일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='졸업일')),
                ('gpa', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='학점')),
                ('status', models.CharField(choices=[('졸업', '졸업'), ('재학', '재학중'), ('중퇴', '중퇴'), ('수료', '수료')], default='졸업', max_length=20, verbose_name='상태')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '학력사항',
                'verbose_name_plural': '학력사항들',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('초급', '초급'), ('중급', '중급'), ('고급', '고급'), ('전문가', '전문가')], default='중급', max_length=20, verbose_name='숙련도')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='경험연수')),
                ('obtained_date', models.DateField(blank=True, null=True, verbose_name='취득일')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.skill', verbose_name='기술')),
            ],
            options={
                'verbose_name': '직원 기술',
                'verbose_name_plural': '직원 기술들',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='증서번호')),
                ('issue_date', models.DateField(verbose_name='발급일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('issuing_organization', models.CharField(blank=True, max_length=100, verbose_name='발급기관')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.certification', verbose_name='자격증')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '직원 자격증',
                'verbose_name_plural': '직원 자격증들',
                'unique_together': {('employee', 'certification', 'certificate_number')},
            },
        ),
    ]
