# Generated by Django 4.2.7 on 2025-09-20 02:15

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="사번",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="전화번호"),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="부서"),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=50, verbose_name="직위"),
                ),
                (
                    "is_hr_manager",
                    models.BooleanField(default=False, verbose_name="인사담당자"),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자")),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="입사일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="core_user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="core_user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resident_id",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="주민등록번호"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="생년월일")),
                (
                    "address",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, verbose_name="주소"
                    ),
                ),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("정규직", "정규직"),
                            ("계약직", "계약직"),
                            ("인턴", "인턴"),
                            ("파견", "파견직"),
                        ],
                        default="정규직",
                        max_length=20,
                        verbose_name="고용형태",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[("전일제", "전일제"), ("시간제", "시간제"), ("재택근무", "재택근무")],
                        default="전일제",
                        max_length=20,
                        verbose_name="근무형태",
                    ),
                ),
                (
                    "position_history",
                    models.JSONField(blank=True, default=list, verbose_name="발령이력"),
                ),
                (
                    "department_history",
                    models.JSONField(blank=True, default=list, verbose_name="부서이력"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("재직", "재직중"),
                            ("휴직", "휴직중"),
                            ("퇴사", "퇴사"),
                            ("정년퇴직", "정년퇴직"),
                        ],
                        default="재직",
                        max_length=20,
                        verbose_name="재직상태",
                    ),
                ),
                (
                    "resignation_date",
                    models.DateField(blank=True, null=True, verbose_name="퇴사일"),
                ),
                (
                    "resignation_reason",
                    models.TextField(blank=True, verbose_name="퇴사사유"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="core.user",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "직원 프로필",
                "verbose_name_plural": "직원 프로필들",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="부서명")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="부서코드"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to="core.user",
                        verbose_name="부서장",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.department",
                        verbose_name="상위부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "부서",
                "verbose_name_plural": "부서들",
                "ordering": ["name"],
            },
        ),
    ]
