# Generated by Django 4.2.7 on 2025-09-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="부서코드"
            ),
        ),
    ]
