# Generated by Django 4.2.7 on 2025-09-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('document_type', models.CharField(choices=[('재직증명서', '재직증명서'), ('경력증명서', '경력증명서'), ('퇴직증명서', '퇴직증명서'), ('급여명세서', '급여명세서'), ('원천징수영수증', '원천징수영수증'), ('근로소득원천징수부', '근로소득원천징수부'), ('고용보험피보험자격취득확인서', '고용보험피보험자격취득확인서'), ('건강보험자격득실확인서', '건강보험자격득실확인서'), ('국민연금가입증명서', '국민연금가입증명서'), ('기타', '기타')], max_length=30, verbose_name='문서유형')),
                ('template_content', models.TextField(verbose_name='템플릿내용')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='변수목록')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본템플릿')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='승인필요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '문서 템플릿',
                'verbose_name_plural': '문서 템플릿들',
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200, verbose_name='교육명')),
                ('training_type', models.CharField(choices=[('내부교육', '내부교육'), ('외부교육', '외부교육'), ('온라인교육', '온라인교육'), ('워크숍', '워크숍'), ('세미나', '세미나'), ('기타', '기타')], default='내부교육', max_length=30, verbose_name='교육유형')),
                ('organization', models.CharField(max_length=100, verbose_name='교육기관')),
                ('instructor', models.CharField(blank=True, max_length=50, verbose_name='강사')),
                ('start_date', models.DateField(verbose_name='교육시작일')),
                ('end_date', models.DateField(verbose_name='교육종료일')),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='총교육시간')),
                ('training_cost', models.PositiveIntegerField(default=0, verbose_name='교육비')),
                ('company_cost', models.PositiveIntegerField(default=0, verbose_name='회사부담금')),
                ('personal_cost', models.PositiveIntegerField(default=0, verbose_name='개인부담금')),
                ('completion_status', models.CharField(choices=[('수료', '수료'), ('수료예정', '수료예정'), ('미수료', '미수료'), ('취소', '취소')], default='수료예정', max_length=20, verbose_name='수료상태')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='성적')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='수료번호')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='training_certificates/', verbose_name='수료증파일')),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True, verbose_name='만족도')),
                ('usefulness_rating', models.IntegerField(blank=True, null=True, verbose_name='유용도')),
                ('feedback', models.TextField(blank=True, verbose_name='교육피드백')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='필수교육')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인완료')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trainings', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '교육이수기록',
                'verbose_name_plural': '교육이수기록들',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('재직증명서', '재직증명서'), ('경력증명서', '경력증명서'), ('퇴직증명서', '퇴직증명서'), ('급여명세서', '급여명세서'), ('원천징수영수증', '원천징수영수증'), ('근로소득원천징수부', '근로소득원천징수부'), ('고용보험피보험자격취득확인서', '고용보험피보험자격취득확인서'), ('건강보험자격득실확인서', '건강보험자격득실확인서'), ('국민연금가입증명서', '국민연금가입증명서'), ('기타', '기타')], max_length=30, verbose_name='문서유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('purpose', models.TextField(verbose_name='용도')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='추가정보')),
                ('special_instructions', models.TextField(blank=True, verbose_name='특별지시사항')),
                ('status', models.CharField(choices=[('신청', '신청완료'), ('검토중', '검토중'), ('승인', '승인'), ('발급완료', '발급완료'), ('수령완료', '수령완료'), ('반려', '반려'), ('취소', '취소')], default='신청', max_length=20, verbose_name='상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('approval_notes', models.TextField(blank=True, verbose_name='승인비고')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='발급일시')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='문서파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL, verbose_name='발급자')),
            ],
            options={
                'verbose_name': '제증명 신청',
                'verbose_name_plural': '제증명 신청들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='계약명')),
                ('contract_type', models.CharField(choices=[('근로계약', '근로계약서'), ('업무협약', '업무협약서'), ('비밀유지', '비밀유지계약'), ('경업금지', '경업금지계약'), ('기타', '기타')], default='근로계약', max_length=30, verbose_name='계약유형')),
                ('counterparty', models.CharField(blank=True, max_length=100, verbose_name='계약상대방')),
                ('content', models.TextField(verbose_name='계약내용')),
                ('key_terms', models.JSONField(blank=True, default=list, verbose_name='주요조항')),
                ('start_date', models.DateField(verbose_name='계약시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='계약종료일')),
                ('contract_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='계약금액')),
                ('payment_terms', models.TextField(blank=True, verbose_name='지급조건')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='계약서파일')),
                ('status', models.CharField(choices=[('작성중', '작성중'), ('검토중', '검토중'), ('서명완료', '서명완료'), ('진행중', '진행중'), ('종료', '종료'), ('해지', '해지')], default='작성중', max_length=20, verbose_name='상태')),
                ('employee_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='직원서명')),
                ('company_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='회사서명')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='서명일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '계약서',
                'verbose_name_plural': '계약서들',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('자격증', '자격증'), ('수료증', '수료증'), ('이수증', '이수증'), ('면허증', '면허증'), ('기타', '기타')], default='자격증', max_length=30, verbose_name='증명서유형')),
                ('name', models.CharField(max_length=100, verbose_name='증명서명')),
                ('issuing_organization', models.CharField(max_length=100, verbose_name='발급기관')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='증서번호')),
                ('issue_date', models.DateField(verbose_name='발급일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='등급')),
                ('score', models.CharField(blank=True, max_length=20, verbose_name='점수')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='증명서파일')),
                ('is_verified', models.BooleanField(default=False, verbose_name='검증완료')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='검증일시')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to=settings.AUTH_USER_MODEL, verbose_name='검증자')),
            ],
            options={
                'verbose_name': '자격증/수료증',
                'verbose_name_plural': '자격증/수료증들',
                'ordering': ['-issue_date'],
            },
        ),
    ]
