# Generated by Django 4.2.7 on 2025-09-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='수당명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='수당코드')),
                ('allowance_type', models.CharField(choices=[('기본수당', '기본수당'), ('직무수당', '직무수당'), ('성과수당', '성과수당'), ('복리후생', '복리후생'), ('기타', '기타')], default='기본수당', max_length=20, verbose_name='수당유형')),
                ('calculation_method', models.CharField(choices=[('정액', '정액'), ('기본급비율', '기본급비율'), ('시급', '시급'), ('일급', '일급'), ('월급', '월급')], default='정액', max_length=20, verbose_name='계산방법')),
                ('default_amount', models.PositiveIntegerField(default=0, verbose_name='기본금액')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='과세대상')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='필수지급')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '수당',
                'verbose_name_plural': '수당들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='공제명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='공제코드')),
                ('deduction_type', models.CharField(choices=[('법정공제', '법정공제'), ('임의공제', '임의공제'), ('기타', '기타')], default='법정공제', max_length=20, verbose_name='공제유형')),
                ('calculation_method', models.CharField(choices=[('정률', '정률'), ('정액', '정액'), ('기본급비율', '기본급비율')], default='정률', max_length=20, verbose_name='계산방법')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='비율')),
                ('default_amount', models.PositiveIntegerField(default=0, verbose_name='기본금액')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='필수공제')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '공제',
                'verbose_name_plural': '공제들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20, unique=True, verbose_name='등급')),
                ('name', models.CharField(max_length=50, verbose_name='등급명')),
                ('base_salary', models.PositiveIntegerField(verbose_name='기본급')),
                ('min_salary', models.PositiveIntegerField(verbose_name='최저급')),
                ('max_salary', models.PositiveIntegerField(verbose_name='최고급')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '급여등급',
                'verbose_name_plural': '급여등급들',
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='RetirementPension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirement_date', models.DateField(verbose_name='퇴직일')),
                ('reason', models.TextField(verbose_name='퇴직사유')),
                ('pension_type', models.CharField(choices=[('확정급여형', '확정급여형 (DB)'), ('확정기여형', '확정기여형 (DC)'), ('개인퇴직연금', '개인퇴직연금 (IRP)')], default='확정기여형', max_length=20, verbose_name='연금유형')),
                ('total_contribution', models.PositiveIntegerField(verbose_name='총납입금')),
                ('employee_contribution', models.PositiveIntegerField(verbose_name='본인납입금')),
                ('company_contribution', models.PositiveIntegerField(verbose_name='회사납입금')),
                ('payout_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='지급금액')),
                ('payout_date', models.DateField(blank=True, null=True, verbose_name='지급일')),
                ('payout_method', models.CharField(choices=[('일시금', '일시금'), ('연금', '연금'), ('혼합', '혼합')], default='일시금', max_length=20, verbose_name='지급방법')),
                ('status', models.CharField(choices=[('계산중', '계산중'), ('확정', '확정'), ('지급완료', '지급완료')], default='계산중', max_length=20, verbose_name='상태')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_pensions', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '퇴직연금',
                'verbose_name_plural': '퇴직연금들',
                'ordering': ['-retirement_date'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('성과상여', '성과상여'), ('명절상여', '명절상여'), ('특별상여', '특별상여'), ('퇴직상여', '퇴직상여'), ('기타', '기타')], max_length=20, verbose_name='상여종류')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('quarter', models.IntegerField(blank=True, null=True, verbose_name='분기')),
                ('amount', models.PositiveIntegerField(verbose_name='상여금액')),
                ('payment_date', models.DateField(verbose_name='지급일')),
                ('reason', models.TextField(blank=True, verbose_name='지급사유')),
                ('status', models.CharField(choices=[('신청', '신청'), ('검토중', '검토중'), ('승인', '승인'), ('지급완료', '지급완료'), ('취소', '취소')], default='신청', max_length=20, verbose_name='상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bonuses', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '상여금',
                'verbose_name_plural': '상여금들',
                'ordering': ['-year', '-quarter', '-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('base_salary', models.PositiveIntegerField(verbose_name='기본급')),
                ('total_allowances', models.PositiveIntegerField(default=0, verbose_name='총수당')),
                ('total_deductions', models.PositiveIntegerField(default=0, verbose_name='총공제')),
                ('gross_pay', models.PositiveIntegerField(verbose_name='지급총액')),
                ('net_pay', models.PositiveIntegerField(verbose_name='실지급액')),
                ('allowances_detail', models.JSONField(blank=True, default=dict, verbose_name='수당내역')),
                ('deductions_detail', models.JSONField(blank=True, default=dict, verbose_name='공제내역')),
                ('payment_date', models.DateField(verbose_name='지급일')),
                ('payment_method', models.CharField(choices=[('계좌이체', '계좌이체'), ('현금', '현금'), ('기타', '기타')], default='계좌이체', max_length=20, verbose_name='지급방법')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='계좌번호')),
                ('status', models.CharField(choices=[('작성중', '작성중'), ('확정', '확정'), ('지급완료', '지급완료'), ('취소', '취소')], default='작성중', max_length=20, verbose_name='상태')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
                ('salary_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarygrade', verbose_name='급여등급')),
            ],
            options={
                'verbose_name': '급여대장',
                'verbose_name_plural': '급여대장들',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
