# Generated by Django 4.2.7 on 2025-09-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('연차', '연차휴가'), ('반차', '반차휴가'), ('병가', '병가'), ('경조사', '경조사휴가'), ('출산휴가', '출산휴가'), ('육아휴가', '육아휴가'), ('기타', '기타휴가')], max_length=20, verbose_name='휴가종류')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('days_requested', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='신청일수')),
                ('reason', models.TextField(verbose_name='사유')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='비상연락처')),
                ('status', models.CharField(choices=[('대기', '승인대기'), ('승인', '승인'), ('반려', '반려'), ('취소', '취소')], default='대기', max_length=20, verbose_name='상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('approval_notes', models.TextField(blank=True, verbose_name='승인비고')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/', verbose_name='첨부파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '휴가 신청',
                'verbose_name_plural': '휴가 신청들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('schedule_type', models.CharField(choices=[('정상근무', '정상근무'), ('휴일근무', '휴일근무'), ('야간근무', '야간근무'), ('특별근무', '특별근무')], default='정상근무', max_length=20, verbose_name='근무유형')),
                ('start_time', models.TimeField(verbose_name='근무시작')),
                ('end_time', models.TimeField(verbose_name='근무종료')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='휴게시작')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='휴게종료')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('is_flexible', models.BooleanField(default=False, verbose_name='탄력근무')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '근무 스케줄',
                'verbose_name_plural': '근무 스케줄들',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('total_days', models.DecimalField(decimal_places=1, default=15, max_digits=4, verbose_name='총 연차일수')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='사용일수')),
                ('remaining_days', models.DecimalField(decimal_places=1, default=15, max_digits=4, verbose_name='잔여일수')),
                ('annual_leave_used', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='연차 사용')),
                ('sick_leave_used', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='병가 사용')),
                ('other_leave_used', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='기타휴가 사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '연차 잔여일수',
                'verbose_name_plural': '연차 잔여일수들',
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('check_in_time', models.DateTimeField(verbose_name='출근시간')),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='출근 IP')),
                ('check_in_location', models.CharField(blank=True, max_length=200, verbose_name='출근 위치')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='퇴근시간')),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='퇴근 IP')),
                ('check_out_location', models.CharField(blank=True, max_length=200, verbose_name='퇴근 위치')),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='근무시간')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='연장근무시간')),
                ('break_hours', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='휴게시간')),
                ('status', models.CharField(choices=[('정상', '정상출근'), ('지각', '지각'), ('조퇴', '조퇴'), ('결근', '결근'), ('휴가', '휴가'), ('외근', '외근'), ('재택', '재택근무')], default='정상', max_length=20, verbose_name='근태상태')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '출퇴근 기록',
                'verbose_name_plural': '출퇴근 기록들',
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
